'use strict';

// Reads the generated block in src/utils/translations.js back into data,
// without importing it: scripts/translations.js needs the values synchronously,
// in commands that are not async. Everything else (build.js,
// check-i18n-split.js) imports the module itself.

const path = require('path');
const vm = require('vm');

const JS_FILE = path.resolve(__dirname, '../../src/utils/translations.js');

// Keys rendered on a dashboard, with no editor open: the half that stays in
// the bundle, in every language.
const BUNDLED_PREFIX = 'card.';

const JS_BLOCK_RE = new RegExp(
  [
    'const TRANSLATION_KEYS = (\\[[\\s\\S]*?\\n\\]);',
    'const EDITOR_KEY_START = (\\d+);',
    'const TRANSLATIONS_CARD = (\\{[\\s\\S]*?\\n\\});',
    'const TRANSLATIONS_EDITOR_EN = (\\[[\\s\\S]*?\\n\\]);',
    'const TRANSLATIONS_EDITOR = (\\{[\\s\\S]*?\\n\\});',
  ].join('\n'),
);

/**
 * Parse the generated block. Returns the five bindings plus `rows`, each
 * language's full value array rebuilt from its two halves.
 * Throws when the block is absent or malformed.
 */
const parseJsBlock = (src) => {
  const blockMatch = src.match(JS_BLOCK_RE);
  if (!blockMatch) throw new Error('TRANSLATION_KEYS/TRANSLATIONS_* block not found in JS file');
  // The block is generated by scripts/translations.js → safe to evaluate in a sandbox.
  const evaluate = (literal) => vm.runInNewContext(`(${literal})`);
  const keys = evaluate(blockMatch[1]);
  const editorStart = Number(blockMatch[2]);
  const card = evaluate(blockMatch[3]);
  const editorEn = evaluate(blockMatch[4]);
  const editor = evaluate(blockMatch[5]);
  const rows = {};
  for (const lang of Object.keys(card)) {
    rows[lang] = [...card[lang], ...(lang === 'en' ? editorEn : (editor[lang] ?? []))];
  }
  return { keys, editorStart, card, editorEn, editor, rows };
};

module.exports = { JS_FILE, BUNDLED_PREFIX, parseJsBlock };
