/*
 * HA_CONTEXT: Home Assistant integration constants - MDI icon ids, theme color
 * CSS-variable names, the HA color name → var map, per-domain attribute
 * mapping, number-format locales, entity state/type/class enums, action
 * shapes, and misc style hooks. No logic, just data.
 */

// from:
// https://github.com/home-assistant/frontend/blob/master/src/resources/theme/color/color.globals.ts
const HA_CONTEXT = {
  icons: {
    prefix: 'mdi:',
    help: 'mdi:help',
    helpCircle: 'mdi:help-circle',
    helpCircleOutline: 'mdi:help-circle-outline',
    chevronUpBox: 'mdi:chevron-up-box',
    chevronDownBox: 'mdi:chevron-down-box',
    equalBox: 'mdi:equal-box',
    progressQuestion: 'mdi:progress-question',
    focusHorizontal: 'mdi:focus-field-horizontal',
    focusVertical: 'mdi:focus-field-vertical',
    alert: 'mdi:alert',
    alertCircleOutline: 'mdi:alert-circle-outline',
    exclamationThick: 'mdi:exclamation-thick',
    play: 'mdi:play',
    pause: 'mdi:pause',
    gestureTapHold: 'mdi:gesture-tap-hold',
    washingMachine: 'mdi:washing-machine',
    update: 'mdi:update',
    lightbulb: 'mdi:lightbulb',
    lightbulbOutline: 'mdi:lightbulb-outline',
    thermometer: 'mdi:thermometer',
    waterPercent: 'mdi:water-percent',
    airFilter: 'mdi:air-filter',
    listBox: 'mdi:list-box',
    textShort: 'mdi:text-short',
    radar: 'mdi:radar',
    aspectRatio: 'mdi:aspect-ratio',
    sizeExtraSmall: 'mdi:size-xs',
    sizeSmall: 'mdi:size-s',
    sizeMedium: 'mdi:size-m',
    sizeLarge: 'mdi:size-l',
    sizeXLarge: 'mdi:size-xl',
  },
  colors: {
    success: 'var(--success-color)',
    stateIcon: 'var(--state-icon-color)',
    red: 'var(--red-color)',
    orange: 'var(--orange-color)',
    deepOrange: 'var(--deep-orange-color)',
    yellow: 'var(--yellow-color)',
    amber: 'var(--amber-color)',
    accent: 'var(--accent-color)',
    deepPurple: 'var(--deep-purple-color)',
    indigo: 'var(--indigo-color)',
    blue: 'var(--blue-color)',
    lightBlue: 'var(--light-blue-color)',
    cyan: 'var(--cyan-color)',
    teal: 'var(--teal-color)',
    green: 'var(--green-color)',
    lightGreen: 'var(--light-green-color)',
    lime: 'var(--lime-color)',
    darkGrey: 'var(--dark-grey-color)',
    unavailable: 'var(--state-unavailable-color)',
    inactive: 'var(--state-inactive-color)',
    active: 'var(--state-active-color)',
    coverActive: 'var(--state-cover-active-color)',
    fanActive: 'var(--state-fan-active-color)',
    batteryLow: 'var(--state-sensor-battery-low-color)',
    batteryMedium: 'var(--state-sensor-battery-medium-color)',
    batteryHigh: 'var(--state-sensor-battery-high-color)',
    climateDry: 'var(--state-climate-dry-color)',
    climateCool: 'var(--state-climate-cool-color)',
    climateHeat: 'var(--state-climate-heat-color)',
    climateFanOnly: 'var(--state-climate-fan_only-color)',
  },
  haColors: new Map(
    [
      // texte
      'primary-text',
      'secondary-text',
      'text-primary',
      'text-light-primary',
      'disabled-text',
      // interface
      'dark-primary',
      'darker-primary',
      'light-primary',
      'divider',
      'outline',
      'outline-hover',
      'shadow',
      // material color
      'primary',
      'accent',
      'red',
      'pink',
      'purple',
      'deep-purple',
      'indigo',
      'blue',
      'light-blue',
      'cyan',
      'teal',
      'green',
      'light-green',
      'lime',
      'yellow',
      'amber',
      'orange',
      'deep-orange',
      'brown',
      'light-grey',
      'grey',
      'dark-grey',
      'blue-grey',
      'black',
      'white',
      // HA
      'success',
      'warning',
      'error',
      'info',
      'disabled',
      // State
      'state-icon',
      'state-active',
      'state-inactive',
      'state-unavailable',
      'state-alarm_control_panel-armed_away',
      'state-alarm_control_panel-armed_custom_bypass',
      'state-alarm_control_panel-armed_home',
      'state-alarm_control_panel-armed_night',
      'state-alarm_control_panel-armed_vacation',
      'state-alarm_control_panel-arming',
      'state-alarm_control_panel-disarming',
      'state-alarm_control_panel-pending',
      'state-alarm_control_panel-triggered',
      'state-alert-off',
      'state-alert-on',
      'state-binary_sensor-active',
      'state-binary_sensor-battery-on',
      'state-binary_sensor-carbon_monoxide-on',
      'state-binary_sensor-gas-on',
      'state-binary_sensor-heat-on',
      'state-binary_sensor-lock-on',
      'state-binary_sensor-moisture-on',
      'state-binary_sensor-problem-on',
      'state-binary_sensor-safety-on',
      'state-binary_sensor-smoke-on',
      'state-binary_sensor-sound-on',
      'state-binary_sensor-tamper-on',
      'state-climate-auto',
      'state-climate-cool',
      'state-climate-dry',
      'state-climate-fan_only',
      'state-climate-heat',
      'state-climate-heat-cool',
      'state-cover-active',
      'state-device_tracker-active',
      'state-device_tracker-home',
      'state-fan-active',
      'state-humidifier-on',
      'state-lawn_mower-error',
      'state-lawn_mower-mowing',
      'state-light-active',
      'state-lock-jammed',
      'state-lock-locked',
      'state-lock-locking',
      'state-lock-unlocked',
      'state-lock-unlocking',
      'state-lock-open',
      'state-lock-opening',
      'state-media_player-active',
      'state-person-active',
      'state-person-home',
      'state-plant-active',
      'state-siren-active',
      'state-sun-above_horizon',
      'state-sun-below_horizon',
      'state-switch-active',
      'state-update-active',
      'state-vacuum-active',
      'state-valve-active',
      'state-sensor-battery-high',
      'state-sensor-battery-low',
      'state-sensor-battery-medium',
      'state-water_heater-eco',
      'state-water_heater-electric',
      'state-water_heater-gas',
      'state-water_heater-heat_pump',
      'state-water_heater-high_demand',
      'state-water_heater-performance',
      'state-weather-clear_night',
      'state-weather-cloudy',
      'state-weather-exceptional',
      'state-weather-fog',
      'state-weather-hail',
      'state-weather-lightning_rainy',
      'state-weather-lightning',
      'state-weather-partlycloudy',
      'state-weather-pouring',
      'state-weather-rainy',
      'state-weather-snowy_rainy',
      'state-weather-snowy',
      'state-weather-sunny',
      'state-weather-windy_variant',
      'state-weather-windy',
    ].map((c) => [c, `var(--${c}-color)`]),
  ),
  attributeMapping: {
    cover: { label: 'cover', attribute: 'current_position' },
    light: { label: 'light', attribute: 'brightness' },
    fan: { label: 'fan', attribute: 'percentage' },
    // No unit_of_measurement on climate/weather - see EntityHelper.unit.
    climate: { label: 'climate', attribute: 'temperature' },
    weather: { label: 'weather', attribute: 'temperature' },
  },
  numberFormat: {
    decimal_comma: 'de-DE', // 1.234,56 (Allemagne, France, etc.)
    comma_decimal: 'en-US', // 1,234.56 (USA, UK, etc.)
    space_comma: 'fr-FR', // 1 234,56 (France, Norvège, etc.)
    quote_decimal: 'de-CH', // 12'345.60 (Switzerland)
  },
  entity: {
    state: {
      unavailable: 'unavailable',
      unknown: 'unknown',
      notFound: 'notFound',
      idle: 'idle',
      active: 'active',
      paused: 'paused',
      on: 'on',
    },
    type: {
      timer: 'timer',
      light: 'light',
      cover: 'cover',
      fan: 'fan',
      climate: 'climate',
      counter: 'counter',
      number: 'number',
      duration: 'duration',
      default: 'default',
    },
    class: { shutter: 'shutter', battery: 'battery' },
  },
  actions: {
    default: 'default',
    navigate: { action: 'navigate' },
    moreInfo: { action: 'more-info' },
    url: { action: 'url' },
    assist: { action: 'assist' },
    toggle: { action: 'toggle' },
    performAction: { action: 'perform-action' },
    none: { action: 'none' },
    toggleDomain: [
      'light',
      'switch',
      'fan',
      'input_boolean',
      'media_player',
      'automation',
      'humidifier',
      'remote',
      'siren',
      'water_heater',
      'vacuum',
      'group',
    ],
  },
  styles: {
    rowSize: '--row-size',
  },
};

export { HA_CONTEXT };
