'use strict';
/**
 * translations.js — unified translation toolchain.
 *
 * Source of truth: translations/<lang>.json (one file per language).
 * template.json is the structural reference (key set), never shipped.
 * The TRANSLATIONS block inside entity-progress-card.js is GENERATED from
 * the JSON files (synchronize --to-js) and must never be edited by hand.
 *
 * Usage: node scripts/translations.js <command> [args]
 * Run without argument for the command list.
 */

const fs = require('fs');
const path = require('path');
const vm = require('vm');
const readline = require('readline');

const ROOT = path.resolve(__dirname, '..');
const DIR = path.join(ROOT, 'translations');
const JS_FILE = path.join(ROOT, 'entity-progress-card.js');
const TEMPLATE = 'template.json';

// ─── generic helpers ─────────────────────────────────────────────────────────

class FatalError extends Error {}
const die = (msg) => { throw new FatalError(`❌ ${msg}`); };
const readJSON = (f) => JSON.parse(fs.readFileSync(f, 'utf8'));
const writeJSON = (f, data) => fs.writeFileSync(f, `${JSON.stringify(data, null, 2)}\n`);
const langFiles = () => fs.readdirSync(DIR).filter((f) => f.endsWith('.json') && f !== TEMPLATE).sort();
const allLangs = () => langFiles().map((f) => f.replace('.json', ''));
const langPath = (lang) => path.join(DIR, `${lang}.json`);

const flatten = (obj, prefix = '', out = {}) => {
  for (const [k, v] of Object.entries(obj)) {
    const keyPath = prefix ? `${prefix}.${k}` : k;
    if (v !== null && typeof v === 'object') flatten(v, keyPath, out);
    else out[keyPath] = v;
  }
  return out;
};

const getPath = (obj, dotted) => dotted.split('.').reduce((o, k) => o?.[k], obj);

/** Insert `key: value` into the object at `parentPath`, after sibling `afterKey` (or append). */
const insertKey = (root, parentPath, key, value, afterKey = null) => {
  const parent = parentPath ? getPath(root, parentPath) : root;
  if (!parent || typeof parent !== 'object') return false;
  if (key in parent) { parent[key] = value; return true; }
  if (!afterKey || !(afterKey in parent)) { parent[key] = value; return true; }
  const rebuilt = {};
  for (const [k, v] of Object.entries(parent)) {
    rebuilt[k] = v;
    if (k === afterKey) rebuilt[key] = value;
  }
  for (const k of Object.keys(parent)) delete parent[k];
  Object.assign(parent, rebuilt);
  return true;
};

const deleteKey = (root, dotted) => {
  const parts = dotted.split('.');
  const key = parts.pop();
  const parent = parts.length ? getPath(root, parts.join('.')) : root;
  if (!parent || !(key in parent)) return false;
  delete parent[key];
  return true;
};

/** Recursively reorder `target` keys to match `reference`; extras are appended (and collected). */
const reorderLike = (reference, target, prefix = '', extras = []) => {
  if (typeof target !== 'object' || target === null) return { result: target, extras };
  const result = {};
  for (const k of Object.keys(reference ?? {})) {
    if (!(k in target)) continue;
    if (reference[k] !== null && typeof reference[k] === 'object' && typeof target[k] === 'object') {
      result[k] = reorderLike(reference[k], target[k], prefix ? `${prefix}.${k}` : k, extras).result;
    } else {
      result[k] = target[k];
    }
  }
  for (const k of Object.keys(target)) {
    if (!(k in result)) {
      extras.push(prefix ? `${prefix}.${k}` : k);
      result[k] = target[k];
    }
  }
  return { result, extras };
};

// ─── JS TRANSLATIONS block I/O ───────────────────────────────────────────────

const JS_BLOCK_RE = /const TRANSLATIONS = (\{[\s\S]*?\n\});/;

const readJsTranslations = () => {
  const src = fs.readFileSync(JS_FILE, 'utf8');
  const blockMatch = src.match(JS_BLOCK_RE);
  if (!blockMatch) die('TRANSLATIONS block not found in JS file');
  // The block is generated by this very tool → safe to evaluate in a sandbox.
  return vm.runInNewContext(`(${blockMatch[1]})`);
};

// Backslashes must be escaped before quotes (order matters), and literal newlines must
// become \n: a translation value containing either would otherwise generate a corrupted
// (or syntactically invalid) TRANSLATIONS block without any error at generation time.
const jsString = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '')}'`;

const formatJS = (obj, indent = 0) => {
  const pad = '  '.repeat(indent);
  const pad1 = '  '.repeat(indent + 1);
  const entries = Object.entries(obj).map(([k, v]) => {
    const needsQuotes = !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k);
    const key = needsQuotes ? jsString(k) : k;
    const val = v !== null && typeof v === 'object' ? formatJS(v, indent + 1) : jsString(v);
    return `${pad1}${key}: ${val}`;
  });
  return `{\n${entries.join(',\n')}\n${pad}}`;
};

const writeJsTranslations = (translations) => {
  const src = fs.readFileSync(JS_FILE, 'utf8');
  // Presence is checked directly: comparing src to the replacement output conflated
  // "block not found" with "block already up to date", making idempotent re-runs die.
  if (!JS_BLOCK_RE.test(src)) die('TRANSLATIONS block not found in JS file');
  fs.writeFileSync(JS_FILE, src.replace(JS_BLOCK_RE, `const TRANSLATIONS = ${formatJS(translations)};`));
};

/** JS source with the TRANSLATIONS block removed — for code-usage searches. */
const jsCodeWithoutTranslations = () => fs.readFileSync(JS_FILE, 'utf8').replace(JS_BLOCK_RE, '');

// ─── diff engine ─────────────────────────────────────────────────────────────

/** Compare two flat maps: what `b` is missing / has extra / has changed vs `a`. */
const diffFlat = (a, b) => {
  const missing = [], extra = [], changed = [];
  for (const k of Object.keys(a)) {
    if (!(k in b)) missing.push(k);
    else if (a[k] !== b[k]) changed.push(k);
  }
  for (const k of Object.keys(b)) if (!(k in a)) extra.push(k);
  return { missing, extra, changed };
};

// ─── commands ────────────────────────────────────────────────────────────────

/** validate: JSON ↔ JS per language + JSON ↔ template structure. Returns issue count. */
const cmdValidate = ({ quiet = false } = {}) => {
  const jsTr = readJsTranslations();
  const template = flatten(readJSON(path.join(DIR, TEMPLATE)));
  let issues = 0;
  const ok = [];

  for (const lang of allLangs()) {
    const json = flatten(readJSON(langPath(lang)));
    const problems = [];

    // 1. JSON ↔ JS (per-language content sync)
    if (!jsTr[lang]) {
      problems.push('  language missing in JS (run: synchronize --to-js)');
    } else {
      const js = flatten(jsTr[lang]);
      const contentDiff = diffFlat(json, js);
      for (const k of contentDiff.missing) problems.push(`  in JSON only (JS outdated): ${k}`);
      for (const k of contentDiff.extra) problems.push(`  in JS only (JSON is the source!): ${k}`);
      for (const k of contentDiff.changed) problems.push(`  value differs (JSON ≠ JS): ${k}`);
    }

    // 2. JSON ↔ template (structural reference)
    const templateDiff = diffFlat(template, json);
    for (const k of templateDiff.missing) problems.push(`  missing vs template: ${k}`);
    for (const k of templateDiff.extra) problems.push(`  not in template: ${k}`);

    if (problems.length) {
      issues += problems.length;
      console.log(`❌ ${lang}`);
      problems.forEach((p) => console.log(p));
    } else {
      ok.push(lang);
    }
  }

  // 3. languages present in JS but with no JSON file
  for (const lang of Object.keys(jsTr)) {
    if (!allLangs().includes(lang)) {
      issues++;
      console.log(`❌ ${lang}: present in JS but has no JSON file (ghost language)`);
    }
  }

  if (!quiet && ok.length) console.log(`✅ ${ok.join(', ')}`);
  console.log(issues === 0 ? '✅ All translations are in sync.' : `❌ ${issues} issue(s). Source of truth: translations/*.json`);
  return issues;
};

const applyToJs = (dryRun) => {
  const fromJson = {};
  for (const lang of allLangs()) fromJson[lang] = readJSON(langPath(lang));
  if (dryRun) {
    const jsTr = readJsTranslations();
    for (const lang of Object.keys(fromJson)) {
      const diff = diffFlat(flatten(fromJson[lang]), flatten(jsTr[lang] ?? {}));
      const changeCount = diff.missing.length + diff.extra.length + diff.changed.length;
      if (changeCount) console.log(`~ ${lang}: +${diff.missing.length} -${diff.extra.length} ~${diff.changed.length}`);
    }
    for (const lang of Object.keys(readJsTranslations())) {
      if (!(lang in fromJson)) console.log(`~ ${lang}: would be removed from JS (no JSON file)`);
    }
    console.log('(dry-run: nothing written)');
    return;
  }
  writeJsTranslations(fromJson);
  console.log(`✅ JS TRANSLATIONS regenerated from JSON (${Object.keys(fromJson).length} languages).`);
};

const applyToJson = (dryRun) => {
  const jsTr = readJsTranslations();
  for (const [lang, tree] of Object.entries(jsTr)) {
    const file = langPath(lang);
    const current = fs.existsSync(file) ? readJSON(file) : {};
    const diff = diffFlat(flatten(tree), flatten(current));
    const changeCount = diff.missing.length + diff.extra.length + diff.changed.length;
    if (!changeCount) continue;
    console.log(`~ ${lang}: +${diff.missing.length} -${diff.extra.length} ~${diff.changed.length}${dryRun ? '' : ' → written'}`);
    if (!dryRun) writeJSON(file, tree);
  }
  if (dryRun) console.log('(dry-run: nothing written)');
  else console.log('✅ JSON files overwritten from the JS block. Review the git diff carefully.');
};

const cmdSynchronize = async (args) => {
  const dryRun = args.includes('--dry-run');
  if (args.includes('--to-js')) { applyToJs(dryRun); return; }
  if (args.includes('--to-json')) { applyToJson(dryRun); return; }

  const issues = cmdValidate({ quiet: true });
  if (issues === 0) return;

  if (!process.stdin.isTTY) {
    console.log('\nRun again with --to-js (nominal flow: JSON → JS) or --to-json (backport a JS-side edit).');
    process.exitCode = 1;
    return;
  }
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const answer = await new Promise((res) => rl.question('\nApply [j] JSON → JS, [s] JS → JSON, [q] quit? ', res));
  rl.close();
  if (answer === 'j') applyToJs(false);
  else if (answer === 's') applyToJson(false);
  else console.log('Nothing done.');
};

/** orphans: heuristic detection of unused translation keys and unresolved localize() paths. */
const cmdOrphans = () => {
  const code = jsCodeWithoutTranslations();
  const en = readJSON(langPath('en'));
  const flat = flatten(en);

  console.log('— Keys never referenced in the code (heuristic: last segment word-search) —');
  console.log('  ⚠️  editor.field.toggle_* keys can be reached dynamically (toggle_<childKey>);');
  console.log('      verify manually before deleting anything.\n');
  let candidates = 0;
  for (const key of Object.keys(flat)) {
    const last = key.split('.').pop();
    const re = new RegExp(`\\b${last.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`);
    if (!re.test(code)) {
      console.log(`  🕳️  ${key}`);
      candidates++;
    }
  }
  if (!candidates) console.log('  none 🎉');

  console.log('\n— localize() literal paths not found in en.json —');
  let broken = 0;
  for (const match of code.matchAll(/localize\(\s*'([^']+)'\s*\)/g)) {
    const localizePath = match[1];
    if (getPath(en, localizePath) === undefined) {
      console.log(`  💥 ${localizePath}`);
      broken++;
    }
  }
  if (!broken) console.log('  none 🎉');
  return candidates + broken === 0 ? 0 : 1;
};

const cmdStats = () => {
  const template = flatten(readJSON(path.join(DIR, TEMPLATE)));
  const total = Object.keys(template).length;
  const rows = allLangs().map((lang) => {
    const templateDiff = diffFlat(template, flatten(readJSON(langPath(lang))));
    const pct = Math.round(((total - templateDiff.missing.length) / total) * 100);
    return { lang, pct, missing: templateDiff.missing.length, extra: templateDiff.extra.length };
  }).sort((a, b) => a.pct - b.pct || a.lang.localeCompare(b.lang));
  console.log(`Reference: ${TEMPLATE} — ${total} keys\n`);
  for (const r of rows) {
    const flag = r.pct === 100 && r.extra === 0 ? '✅' : '⚠️ ';
    console.log(`${flag} ${r.lang.padEnd(8)} ${String(r.pct).padStart(3)}%  missing:${String(r.missing).padStart(3)}  extra:${r.extra}`);
  }
};

const parseFlag = (args, name) => {
  const flagIndex = args.indexOf(name);
  return flagIndex >= 0 && args[flagIndex + 1] ? args[flagIndex + 1] : null;
};

const cmdAddKey = (args) => {
  // positional args = anything that is neither a flag nor the value following a flag
  const flagValueIndexes = new Set(
    ['--values', '--after', '--en'].map((flag) => args.indexOf(flag) + 1).filter((index) => index > 0)
  );
  const [keyPath] = args.filter((arg, index) => !arg.startsWith('--') && !flagValueIndexes.has(index));
  if (!keyPath || !keyPath.includes('.')) die('usage: add-key <dotted.path> (--values <file.json> | --en "<text>") [--after <siblingKey>]');
  const valuesFile = parseFlag(args, '--values');
  const enText = parseFlag(args, '--en');
  const after = parseFlag(args, '--after');
  const values = valuesFile ? readJSON(valuesFile) : {};
  if (enText) values.en = enText;
  if (!values.en) die('an English value is required (--en or an "en" entry in --values)');

  const parts = keyPath.split('.');
  const key = parts.pop();
  const parentPath = parts.join('.');

  for (const lang of allLangs()) {
    const data = readJSON(langPath(lang));
    if (!insertKey(data, parentPath, key, values[lang] ?? values.en, after)) die(`parent "${parentPath}" not found in ${lang}.json`);
    writeJSON(langPath(lang), data);
  }
  const tpl = readJSON(path.join(DIR, TEMPLATE));
  insertKey(tpl, parentPath, key, values.en, after);
  writeJSON(path.join(DIR, TEMPLATE), tpl);
  console.log(`✅ ${keyPath} added to ${allLangs().length} languages + template (${Object.keys(values).length} translated, rest fell back to en).`);
  console.log('Now run: node scripts/translations.js synchronize --to-js');
};

const cmdRenameKey = (args) => {
  const [oldPath, newPath] = args.filter((a) => !a.startsWith('--'));
  if (!oldPath || !newPath) die('usage: rename-key <old.dotted.path> <new.dotted.path>');
  const oldParts = oldPath.split('.'), newParts = newPath.split('.');
  const sameParent = oldParts.slice(0, -1).join('.') === newParts.slice(0, -1).join('.');

  const renameIn = (file) => {
    const data = readJSON(file);
    const value = getPath(data, oldPath);
    if (value === undefined) return false;
    if (sameParent) {
      // in-place rename preserving key order
      const parent = getPath(data, oldParts.slice(0, -1).join('.')) ?? data;
      const oldKey = oldParts.at(-1), newKey = newParts.at(-1);
      const rebuilt = {};
      for (const [k, v] of Object.entries(parent)) rebuilt[k === oldKey ? newKey : k] = v;
      for (const k of Object.keys(parent)) delete parent[k];
      Object.assign(parent, rebuilt);
    } else {
      deleteKey(data, oldPath);
      insertKey(data, newParts.slice(0, -1).join('.'), newParts.at(-1), value);
    }
    writeJSON(file, data);
    return true;
  };

  let renamedCount = 0;
  for (const lang of allLangs()) if (renameIn(langPath(lang))) renamedCount++;
  renameIn(path.join(DIR, TEMPLATE));
  console.log(`✅ renamed in ${renamedCount} languages + template. Remember to update the code, then: synchronize --to-js`);
};

const cmdRemoveKey = (args) => {
  const [keyPath] = args.filter((a) => !a.startsWith('--'));
  if (!keyPath) die('usage: remove-key <dotted.path>');
  let removedCount = 0;
  for (const lang of allLangs()) {
    const data = readJSON(langPath(lang));
    if (deleteKey(data, keyPath)) { writeJSON(langPath(lang), data); removedCount++; }
  }
  const tpl = readJSON(path.join(DIR, TEMPLATE));
  if (deleteKey(tpl, keyPath)) writeJSON(path.join(DIR, TEMPLATE), tpl);
  console.log(`✅ ${keyPath} removed from ${removedCount} languages + template. Now run: synchronize --to-js`);
};

const cmdFill = (args) => {
  const [lang] = args.filter((a) => !a.startsWith('--') && a !== parseFlag(args, '--from'));
  if (!lang) die('usage: fill <lang> [--from <lang=en>] [--mark]');
  const from = parseFlag(args, '--from') ?? 'en';
  const mark = args.includes('--mark');
  if (!fs.existsSync(langPath(lang))) die(`${lang}.json does not exist (use new-lang)`);
  const source = readJSON(langPath(from));
  const target = readJSON(langPath(lang));
  const srcFlat = flatten(source), tgtFlat = flatten(target);
  let filled = 0;
  for (const [key, value] of Object.entries(srcFlat)) {
    if (key in tgtFlat) continue;
    const parts = key.split('.');
    insertKey(target, parts.slice(0, -1).join('.'), parts.at(-1), mark ? `[TODO] ${value}` : value);
    filled++;
  }
  // normalize order to the source language for clean diffs
  const { result } = reorderLike(source, target);
  writeJSON(langPath(lang), result);
  console.log(`✅ ${lang}: ${filled} key(s) filled from ${from}${mark ? ' (marked [TODO])' : ''}. Now run: synchronize --to-js`);
};

const cmdSort = () => {
  const template = readJSON(path.join(DIR, TEMPLATE));
  for (const lang of allLangs()) {
    const { result, extras } = reorderLike(template, readJSON(langPath(lang)));
    writeJSON(langPath(lang), result);
    if (extras.length) console.log(`⚠️  ${lang}: keys not in template appended at end: ${extras.join(', ')}`);
  }
  console.log(`✅ ${allLangs().length} files reordered to match ${TEMPLATE}. Now run: synchronize --to-js`);
};

const cmdNewLang = (args) => {
  const [code] = args.filter((a) => !a.startsWith('--'));
  if (!code) die('usage: new-lang <code> [--mark]');
  if (fs.existsSync(langPath(code))) die(`${code}.json already exists`);
  const mark = args.includes('--mark');
  const en = readJSON(langPath('en'));
  const markTree = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) =>
    [k, typeof v === 'object' && v !== null ? markTree(v) : (mark ? `[TODO] ${v}` : v)]));
  writeJSON(langPath(code), markTree(en));
  console.log(`✅ ${code}.json created from en${mark ? ' (all values marked [TODO])' : ''}.`);
  console.log('Translate it, then run: synchronize --to-js');
};

// ─── entry point ─────────────────────────────────────────────────────────────

const HELP = `translations.js — unified translation toolchain (source of truth: translations/*.json)

  validate                     compare JSON ↔ JS ↔ template, report every drift (exit 1 if any)
  synchronize [--to-js|--to-json] [--dry-run]
                               validate then apply: JSON → JS (nominal) or JS → JSON (backport)
  orphans                      heuristic: translation keys unused by the code + broken localize() paths
  stats                        per-language coverage vs template.json
  add-key <path> (--values <file>|--en "<text>") [--after <sibling>]
                               add a key to every language + template (fallback: en value)
  rename-key <old> <new>       rename/move a key everywhere (order preserved)
  remove-key <path>            delete a key everywhere
  fill <lang> [--from en] [--mark]
                               copy missing keys from another language ([TODO]-mark optional)
  sort                         reorder every JSON to match template.json key order
  new-lang <code> [--mark]     bootstrap a new language file from en

After any change: synchronize --to-js regenerates the JS block. Never edit it by hand.`;

const main = async () => {
  const [cmd, ...args] = process.argv.slice(2);
  try {
    switch (cmd) {
      case 'validate': process.exitCode = cmdValidate() === 0 ? 0 : 1; break;
      case 'synchronize': await cmdSynchronize(args); break;
      case 'orphans': process.exitCode = cmdOrphans(); break;
      case 'stats': cmdStats(); break;
      case 'add-key': cmdAddKey(args); break;
      case 'rename-key': cmdRenameKey(args); break;
      case 'remove-key': cmdRemoveKey(args); break;
      case 'fill': cmdFill(args); break;
      case 'sort': cmdSort(); break;
      case 'new-lang': cmdNewLang(args); break;
      default: console.log(HELP);
    }
  } catch (error) {
    if (!(error instanceof FatalError)) throw error;
    console.error(error.message);
    process.exitCode = 1;
  }
};

main();
