name: Assign issues to Ko4la

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to Ko4la
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue edit ${{ github.event.issue.number }} --add-assignee francois-le-ko4la --repo ${{ github.repository }}
