name: Assign issues to Ko4la

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to Ko4la
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: francois-le-ko4la
